source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MRWorldMapView_Example', :exclusive => true do
  pod "MRWorldMapView", :path => "../"
end

target 'MRWorldMapView_Tests', :exclusive => true do
  pod "MRWorldMapView", :path => "../"

  
end
